### ISSUE TITLE
Tracking issue for final release of Theme 2.0

### ISSUE THREAD

**Issue by bundyo** [NativeScript/theme#160]
* [x] Merge next branch in master for better visibility
* [ ] Issue NativeScript/NativeScript#7313 should be merged for 6.1 release.
* [ ] Make sure the compat styles are working and up to date.
* [ ] Proper documentation in NativeScript Docs.
* [ ] 1.x to 2.x migration guide.

Extended Goals:
* [ ] Style the remaining nativescript-ui components, when they become styleable.
* [ ] Component authors style guide and best practices.
